metadata/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.static import serve
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mydatasets.urls')),
    url(r'^mydatasets/', include('mydatasets.urls', namespace='mydatasets')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^login/$', auth_views.login, {'template_name': 'mydatasets/templates/mydatasets/login.html'},
        name='meta_login'),
    url(r'^logout/$', auth_views.logout,
        {'next_page': reverse_lazy('dataset_list')}, name='meta_logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydatasets/urls.py
from django.conf.urls import url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView

from models import Dataset, Neuron
from forms import DatasetForm, NeuronForm
from views import *
from views import DatasetCreate, NeuronCreate, DatasetDetail, NeuronUpdate
from views import neuron_duplicate
from views import add_dataset, edit_dataset
from views import add_neuron, edit_neuron
from views import add_neuron_author
from views import generate_csv
from views import neuron_delete
from views import delete_dataset
from views import search
from views import review
from views import delete_review
from views import dataset_list
from views import dataset_detail
from views import about
from views import dataset_duplicate
from views import proof_entry
from views import dataset_status
from views import upload
from views import change_propagate
from views import dataset_archive_status
from views import archive_list
from views import version_new_terms
from views import manage
from views import dataset_public_status
from views import prepopulate
from views import neuron_groups_delete
from views import handler404, handler500

# from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy


urlpatterns = [

	# list all the available datasets and sort them based on time
	url(r'^$', dataset_list, name='dataset_list'),

	# Search in dataset
	url(r'^search/?$', search, name = 'search'),

	# dataset details, ex.: /mydatasets/dataset/1/
    url(r'^datasets/(?P<pk>\d+)/$',
        dataset_detail,
        name='dataset_detail'),

	# dataset neuron details, ex: /mydatasets/dataset/1/neurons/1/
    url(r'^datasets/(?P<pkr>\d+)/neuron/(?P<pk>\d+)/\$',
        DetailView.as_view(
        	model=Neuron,
        	template_name='mydatasets/neuron_detail.html'),
        name='neuron_detail'),

	# Create a dataset, /mydatasets/dataset/create/
    url(r'^datasets/create/\$', DatasetCreate.as_view(), name='dataset_create'),
    url(r'^datasets/create2/\$', add_dataset, name='add_dataset'),

	# Edit dataset details, ex.: /datasets/dataset/1/edit/
    url(r'^datasets/(?P<pk>\d+)/edit/\$',
        UpdateView.as_view(
        	model = Dataset,
        	template_name = 'mydatasets/form.html',
        	form_class = DatasetForm,
            success_url=reverse_lazy('dataset_list')
            ),
        name='dataset_edit'),
	url(r'^datasets/(?P<pk>\d+)/edit2/\$', edit_dataset, name='edit_dataset' ),

	# duplicate a group of neurons, ex.: /mydatasets/datasets/1/duplicate/
	url(r'^datasets/(?P<pkr>\d+)/duplicate/$',
		dataset_duplicate,
		name='dataset_duplicate'),

	# Create a group of neurons, ex.: /mydatasets/datasets/1/neurons/create/
	url(r'^datasets/(?P<pk>\d+)/neurons/create/$', add_neuron, name='neuron_create'),
	url(r'^datasets/(?P<pk>\d+)/neurons/create2/$', add_neuron_author, name='neuron_create2'),

	# remove all groups
	url(r'^datasets/(?P<pk>\d+)/neurons/deleteall/$', neuron_groups_delete, name='neuron_groups_delete'),

	# Edit dataset neuron details, ex.: /mydatasets/datasets/1/neurons/1/edit/
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/edit/$', edit_neuron, name='neuron_edit'),
	# make changes and propagate them to other groups
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/propagate/$', change_propagate, name='change_propagate'),
	# prepopulate the current from from the inforamtion of previous group
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/prepopulate/$', prepopulate, name='prepopulate'),

	# proof new entry
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/proof/$', proof_entry, name='proof_entry'),

	# Create a dataset review, ex.: /mydatasets/datasets/1/reviews/create/
	# Unlike the previous patterns, this one is implemented using a method view instead of a class view
    url(r'^datasets/(?P<pk>\d+)/reviews/create/$', review, name='create_review'),
    # delete a review
	url(r'^datasets/(?P<pkr>\d+)/reviews/(?P<pk>\d+)/delete/$', delete_review, name='delete_review'),

	# upload
	url(r'^datasets/(?P<pk>\d+)/upload-files/$', upload, name='upload'),

	# duplicate a group of neurons, ex.: /mydatasets/datasets/1/neurons/1/duplicate/
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/duplicate/$',
		neuron_duplicate,
		name='neuron_duplicate'),
	
	# delete a group of neurons, ex.: /mydatasets/datasets/1/neurons/1/delete/
	url(r'^datasets/(?P<pkr>\d+)/neurons/(?P<pk>\d+)/delete/$',
		neuron_delete,
		name='neuron_delete'),
    
	# generate csv url
	url(r'^datasets/(?P<pk>\d+)/generatecsv/\$', generate_csv, name='generate_csv' ),
    
	# change dataset status
	url(r'^datasets/(?P<pk>\d+)/change-status/\$', dataset_status, name='dataset_status' ),
    
	# change dataset archive status
	url(r'^datasets/(?P<pk>\d+)/change-archive-status/\$', dataset_archive_status, name='dataset_archive_status' ),
    
	# change dataset public status
	url(r'^datasets/(?P<pk>\d+)/change-public-status/\$', dataset_public_status, name='dataset_public_status' ),
    
	# delete a dataset
	url(r'^datasets/(?P<pk>\d+)/delete-dataset/\$', delete_dataset, name='delete_dataset' ),
    
	# about page
	url(r'^about/$', about, name='about' ),
    
	# archive page
	url(r'^archives/$', archive_list, name='archive_list' ),
    
	# clean up
	url(r'^manage/$', manage, name='manage' ),
    
	# new terms page
	url(r'^new_terms/$', version_new_terms, name='version_new_terms' ),

	# load celltype level 2
	url('ajax/second_level/', second_level, name = 'second_level')

]

handler404 = handler404
handler500 = handler500

mydatasets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import sys
from datetime import date, datetime

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
from django.db import models

reload(sys)  
sys.setdefaultencoding('utf-8')



class Version(models.Model):
    """keep track of release versions"""
    title = models.CharField(max_length=500)
    features = models.TextField(blank=True, null=True)
    date = models.DateTimeField('date created', default=datetime.now, blank=True)
    def features_as_list(self):
        return self.features.split('\n')
    def __unicode__(self):
        return "%s - %s"%(self.title, self.features[0:50] + '...')

# modify uploading location
def upload_location(instance, filename):
    print 'changing location'
    print "{}/{}".format(instance.archive_name, filename)
    return "files/"
    return "{}/{}".format(instance.archive_name, filename)

class Dataset(models.Model):
    """containing datasets"""
    # name = models.CharField(max_length=500)
    archive_name = models.CharField(max_length=500, blank=True, null=True)
    identifier = models.IntegerField('PMID', blank=True, null=True)
    authors = models.CharField(max_length=500, blank=True, null=True)
    url = models.URLField('URL', blank=True, null=True)
    nmo_version = models.CharField('NMO Version', max_length=500, blank=True)
    date = models.DateTimeField('date created', default=datetime.now, blank=True)
    deposition_date = models.DateField('deposition date', default=datetime.now, blank=True)
    notes = models.TextField(blank=True)
    grant_id = models.TextField(blank=True)
    # management fields
    user = models.ForeignKey(User, default=1)
    review = models.BooleanField(default=False, blank=True)
    set_archive = models.BooleanField(default=False, blank=True)
    public = models.BooleanField(default=False, blank=True)
    # file fields
    pdf = models.FileField(upload_to=upload_location, blank=True)
    excel = models.FileField(upload_to=upload_location, blank=True)
    reconstructions = models.FileField(upload_to=upload_location, blank=True)
    def clean_grant_id(self):
        string = self.cleaned_data['grant_id']
        string = re.sub('[^A-Za-z0-9 ]+', '', string)
        string = re.sub('\s\s+', ' ', string)
        if len(message) >= 5000:
            raise ValidationError('Too many characters ...')
        return string
    def __unicode__(self):
        return "%s - %s"%(self.identifier, self.archive_name)
    def name(self):
        return "%s%s"%(self.archive_name)
    def id(self):
        return "%s%s"%(self.identifier)


class Species(models.Model):
    species    = models.CharField(unique=True, max_length=500)
    species_id = models.IntegerField(blank=True, null=True)
    version    = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.species
    class Meta:
        ordering = ('species', )
    
class Gender(models.Model):
    gender  = models.CharField(unique=True, max_length=500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    # species = models.ForeignKey(Species)
    def __str__(self):
        return "{}".format(self.gender)
    class Meta:
        ordering = ('gender', )

class Development(models.Model):
    age_class_id   = models.IntegerField(blank=True, null=True)
    age_class   = models.CharField(unique=True, max_length=500, blank=True, null=True)
    version   = models.CharField(max_length=100, blank=True, null=True)
    # species = models.ForeignKey(Species, null=True)
    def __str__(self):
        return "{}".format(self.age_class)
    class Meta:
        ordering = ('age_class', )

class BrainRegion1(models.Model):
    region1_id = models.IntegerField(blank=True, null=True)
    region1 = models.CharField(unique=True, max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return "{}".format(self.region1)
    class Meta:
        ordering = ('region1', )

class BrainRegion2(models.Model):
    region1 = models.ForeignKey(BrainRegion1, null=True, blank=True)
    region2_id = models.IntegerField(blank=True, null=True)
    region2 = models.CharField(max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    class Meta:
        ordering = ('region2', )
        unique_together = ('region1', 'region2', )
    def __str__(self):
        return "{}".format(self.region2)
    @property
    def level(self):
        return "({}) {}".format(self.region1, self.region2)

class BrainRegion3(models.Model):
    region1 = models.ForeignKey(BrainRegion1, null=True, blank=True)
    region2 = models.ForeignKey(BrainRegion2, null=True, blank=True)
    region3_id = models.IntegerField(blank=True, null=True)
    region3 = models.CharField(max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    class Meta:
        ordering = ('region3', )
        unique_together = ('region1', 'region2', 'region3', )
    def __str__(self):
        return "{}".format(self.region3)
    @property
    def level(self):
        return "({} ➡ {}) {}".format(self.region1, self.region2, self.region3)

class CellType1(models.Model):
    class1_id = models.IntegerField(blank=True, null=True)
    class1 = models.CharField(unique=True, max_length = 500)
    version   = models.CharField(max_length=100, blank=True,  null=True)
    def __str__(self):
        return "{}".format(self.class1)
    class Meta:
        ordering = ('class1', )

class CellType2(models.Model):
    class1 = models.ForeignKey(CellType1, null=True, blank=True)
    class2_id = models.IntegerField(blank=True, null=True)
    class2  = models.CharField(max_length = 500)
    version = models.CharField(max_length=100, blank=True,  null=True)
    class Meta:
        ordering = ('class2', )
        unique_together = ('class1', 'class2', )
    def level(self):
        return "{}-{}".format(self.class1, self.class2)
    def __str__(self):
        return "{}".format(self.class2)
    @property
    def level(self):
        return "({}) {}".format(self.class1, self.class2)

class CellType3(models.Model):
    class1 = models.ForeignKey(CellType1, null=True, blank=True)
    class2 = models.ForeignKey(CellType2, null=True, blank=True)
    class3_id = models.IntegerField(blank=True, null=True)
    class3 = models.CharField(max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    class Meta:
        ordering = ('class3', )
        unique_together = ('class1', 'class2', 'class3', )
    def __str__(self):
        return "{}".format(self.class3)
    @property
    def level(self):
        return "({} ➡ {}) {}".format(self.class1, self.class2, self.class3)

class SlicingDirection(models.Model):
    direction_id = models.IntegerField(null=True, blank=True)
    slicing_direction = models.CharField(unique=True, max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return unicode("{}".format(self.slicing_direction))
    class Meta:
        ordering = ('slicing_direction', )

class StainMethod(models.Model):
    stain_id = models.IntegerField(null=True, blank=True)
    stain = models.CharField(unique=True, max_length = 500)
    version   = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return "{}".format(self.stain)
    class Meta:
        ordering = ('stain', )

class Strain(models.Model):
    species = models.ForeignKey(Species, blank=True, null=True, on_delete=models.SET_NULL)
    strain_id = models.IntegerField(null=True, blank=True)
    strain_name = models.CharField(max_length = 500, null=True, blank=True)
    # scientific_name = models.CharField(max_length = 500, null=True, blank=True)
    version   = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ('strain_name', )
        unique_together = ('strain_name', 'species', )
    def __str__(self):
        return "{}".format(self.strain_name)
    @property
    def level(self):
        return "({}) {}".format(self.species, self.strain_name)
        

class ReconstructionSoftware(models.Model):
    reconstruction_id = models.IntegerField(null=True, blank=True)
    reconstruction_software = models.CharField(unique=True, max_length = 500, null=True, blank=True)
    version   = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return "{}".format(self.reconstruction_software)
    class Meta:
        ordering = ('reconstruction_software', )


class ObjectiveType(models.Model):
    objective_id = models.IntegerField(null=True, blank=True)
    objective_type = models.CharField(unique=True, max_length = 500, null=True, blank=True)
    version   = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return "{}".format(self.objective_type)
    class Meta:
        ordering = ('objective_type', )

class ProtocolDesign(models.Model):
    protocol_id = models.IntegerField(null=True, blank=True)
    protocol = models.CharField(unique=True, max_length = 500, null=True, blank=True)
    version   = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return "{}".format(self.protocol)
    class Meta:
        ordering = ('protocol', )

class ExperimentCondition(models.Model):
    expercond_id = models.IntegerField(null=True, blank=True)
    expercond = models.CharField(unique=True, max_length = 500, null=True, blank=True)
    version   = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return "{}".format(self.expercond)
    class Meta:
        ordering = ('expercond', )

mydatasets/templates/mydatasets/about.html
{% extends "mydatasets/base.html" %} {% block content %}

{% block address %}
<a style="font-size: 15px; margin-left: -28px" class="navbar-brand" href="#">
<sub> <span class="glyphicon glyphicon-triangle-right"></span>About
</a>
{% endblock %}

<h3>
  <span>
    <i class="glyphicon glyphicon-exclamation-sign"></i>
  </span>
  About
</h3>


<div class="well well">
  <h2 class="display-3">NeuroMorpho.Org Metadata Portal</h2>
  <p class="lead">
    This portal is a smart meta-data acquisition portal to facilitate data management process in NeuroMorpho.Org. 
  </p>
</div>
  
<hr>

<ul class="list-unstyled">
  {% for version in versions %}
  <li class="well well-sm">
      <h3>
        {{version.title}}
      </h4>
      <ul>
        {% for line in version.features_as_list%}
        <li>{{line|safe}}</li>
        {% endfor %}
      </ul>
  </li>
  {% empty %}
  <li>No versions yet!</li>
  {% endfor %}
</ul>

{% if versions.has_other_pages %}
<div class="text-center">
  <ul class="pagination">
    {% if versions.has_previous %}
      <li><a href="?page={{ post.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in versions.paginator.page_range %}
      {% if versions.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if versions.has_next %}
      <li><a href="?page={{ versions.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}



{% endblock %}

mydatasets/templates/mydatasets/confirmation.html
{% load  app_filters %}

{% if entry|length > 0 and request.user|has_group:"Proof" %}
    <form class="form-inline" name="create_station" method="post" action="{% url 'mydatasets:proof_entry'  neuron.dataset.id neuron.id %}">
        {% csrf_token %}
        <input type="hidden" name="table"   value={{table}} />
        <input type="hidden" name="entry"   value="{{entry}}" />
        <input type="hidden" name="parent"  value="{{parent}}" />
        <input type="hidden" name="parent1" value="{{parent1}}" />
        <!-- <input type="submit" name="for_one" value="proof and add to this group?" /> -->
        <input type="submit" class="btn btn-success btn-xs" name="for_all" value="Proof `{{entry}}`?" />
    </form>
{% elif entry|length > 0 and not request.user|has_group:"Proof" %}
<font color="red">(New!)</font>
{% endif %}

mydatasets/templates/mydatasets/datasets.html
<hr>

{% comment %}
<ul class="list-unstyled">
  {% for dataset in datasets %}
  <li class="well well-sm">
    <div class="row">
      <div class="col-sm-10">
          <a href="{% url 'mydatasets:dataset_detail' dataset.id %}">
            <h4>
              Archive: {{ dataset.archive_name }} 
              <span class="badge badge-pill badge-primary">{{dataset.nmo_version}}</span>
              {% if dataset.review  %}
                [ready to review]
              {% endif %}
            </h4>
          </a>
      
          <b>Article ID:</b> {{ dataset.identifier }}
      
          <br>
          <b>Article url:</b> <a href="{{ dataset.url }}">{{ dataset.url }}</a>
      
          <br>
          <b>Author(s):</b> {{ dataset.authors }}
      
          <br>
          ----
          <br>
          added by <b>{{ dataset.user|title }}</b> {{ dataset.date|timesince }} ago!
          
      </div>
      <div class="col-sm-2">
        <div class="btn-group-vertical">
          {% if user.is_superuser %}
          <a class="btn btn-info btn-sm" href="{% url 'mydatasets:dataset_duplicate' dataset.id %}"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Duplicate </a> 
          <a class="btn btn-success btn-sm" href="{% url 'mydatasets:generate_csv' dataset.id %}"> <span class="glyphicon glyphicon-save"></span> Get CSV </a>    
          <a class="btn btn-primary btn-sm" href="{% url 'mydatasets:dataset_archive_status' dataset.id %}" onclick="return ConfirmArchive()"> <span class="glyphicon glyphicon-folder-close"></span> Archive </a>    
          <a class="btn btn-danger btn-sm" href="{% url 'mydatasets:delete_dataset' dataset.id %}" onclick="return ConfirmDelete()"> <span class="glyphicon glyphicon-remove"></span> Delete </a>    
          {% elif user == dataset.user %}
          <a class="btn btn-danger btn-sm" href="{% url 'mydatasets:delete_dataset' dataset.id %}" onclick="return ConfirmDelete()"> <span class="glyphicon glyphicon-remove"></span> Delete </a>    
          {% endif %}
        </div>
      </div>
    </div>

    {% if not dataset.user.is_superuser %}
    <div class="row">
      <div class="col-sm-5">
      </div>
      <div class="col-sm-2">
        <span class = "label label-info">Author's entry (public)</span>
      </div>
      <div class="col-sm-5">
      </div>
    </div>
    {%endif%}

  </li>
  {% empty %}
  {% if archive %}
    <li>No Arvhives!</li>
  {% else %}
    <li>No datasets is inserted yet!</li>
  {% endif %}
  {% endfor %}
</ul>


{% if datasets.has_other_pages %}
<div class="text-center">
  <ul class="pagination">
    {% if datasets.has_previous %}
      <li><a href="?page={{ post.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in datasets.paginator.page_range %}
      {% if datasets.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if datasets.has_next %}
      <li><a href="?page={{ datasets.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}

{% endcomment %}

<div id="dataset_tables"></div>
<table class="table table-bordered table-hover table-striped" cellspacing="0" width="100%" id="datasets">
  <thead>
    <tr>
      <td>ID</td>
      <td>Dataset</td>
      <td>Author</td>
      <td class="col-xs-1 text-center">Version</td>
      <td>Status</td>
      <td class="col-xs-1 text-center">Created</td>
      <td class="text-center">Management</td>
    </tr>
  </thead>
  <tbody>
    {% for dataset in datasets %}
    <tr {% if dataset.review %} class="info" {% endif %} >
      <td>{{dataset.identifier}}</td>
      <td> <a href="{% url 'mydatasets:dataset_detail' dataset.id %}"> {{dataset.archive_name}} </a> </td>
      <td>{{dataset.authors|title|truncatechars:15}}</td>
      <!-- <td>{{dataset.nmo_version}}</td> -->
      <td class="text-center"><span class="badge badge-pill badge-primary">{{dataset.nmo_version|default:"?"}}</span></td>
      <td>{{dataset.review|yesno:"Ready!,Ongoing..."}}</td>
      <td> <span style="display:none">{{dataset.date|date:"Ymd-h:m:s" }}</span> {{dataset.date|date:"d/M/y" }}</td>
      <!-- buttons -->
      <td class="text-center">
        {% if user.is_superuser %}
          <a class="btn btn-info btn-sm"    title="duplicate dataset" href="{% url 'mydatasets:dataset_duplicate' dataset.id %}#dataset_table"> <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span></a> 
          <a class="btn btn-success btn-sm" title="download CSV file" href="{% url 'mydatasets:generate_csv' dataset.id %}"> <span class="glyphicon glyphicon-download-alt"></span></a>    
          <a class="btn btn-primary btn-sm" title="make (archive/unarchive)" href="{% url 'mydatasets:dataset_archive_status' dataset.id %}#dataset_table" onclick="return ConfirmArchive()"> <span class="glyphicon glyphicon-ok"></span></a>
          <a class="btn btn-danger btn-sm"  title="delete dataset" href="{% url 'mydatasets:delete_dataset' dataset.id %}#dataset_table" onclick="return ConfirmDelete()"> <span class="glyphicon glyphicon-trash"></span></a>    
          {% elif user == dataset.user %}
          <a class="btn btn-danger btn-sm"  title="delete dataset" href="{% url 'mydatasets:delete_dataset' dataset.id %}#dataset_table" onclick="return ConfirmDelete()"> <span class="glyphicon glyphicon-trash"></span></a>    
        {%endif%}
      </td>
    </tr>
    {%endfor%}
  </tbody>
</table>

mydatasets/templates/mydatasets/search_results.html
{% extends "mydatasets/base.html" %}

{% block address %}
  <a style="font-size: 15px; margin-left: -28px" class="navbar-brand" href="#">
  <sub> <span class="glyphicon glyphicon-triangle-right"></span>Search
  </a>
{% endblock %}

{% block content %}
    
<h3>
  <span class="glyphicon glyphicon-list"></span> Dataset Search...
</h3>


<div class="well well">
  <div class="btn-toolbar">
    <div class="row">
      <div class="col-sm-9">
        <!-- {% if user == neuron.user or user.is_superuser%} -->
        <p>Search for <strong>{{ query }}</strong>, resulted in <strong>{{datasets|length}}</strong> datasets!</p>
        <!-- <a class="btn btn-primary" href="{% url 'mydatasets:add_dataset' %}"> <span class="glyphicon glyphicon-plus"></span> New Dataset</a>   -->
        <!-- <a class="btn btn-success" href="">Reports <span class="glyphicon glyphicon-stats"></span> </a> -->
        <!-- {% endif %} -->
      </div>
      <div class="col-sm-3">
        
        <form type="get" action="{% url 'mydatasets:search' %}">
            <div class="input-group">

              <input type="search" class="form-control" id="q" name="q" placeholder="Search..."/>
              <div class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </div> <!-- input group btn -->
            </div> <!-- input group -->
          </form>

      </div>
    </div>
  </div>
</div>
  
<!-- list all the datasets -->
{% include "mydatasets/datasets.html" %}


{% endblock %}